env:
  browser: true

extends:
  - plugin:cheatsheet/core
  - plugin:cheatsheet/react
  - plugin:cheatsheet/testing

globals:
  Cypress: false
  cy: false

overrides:
- files:
  - "*"
  rules:
    "@typescript-eslint/member-delimiter-style":
    - error
    - singleline:
        delimiter: semi
